baseURL = "https://www.benolanlokun.com/"
relativeURLs = true
languageCode = 'en-us'
title = 'Ben Olanlokun'
theme = 'paper'
publishDir = "public"
pluralizeListTitles = false
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  math = true

customcss = [
	"css/settings.css",
	"css/theme.css",
	"css/styles.css"
]
